[package]
org = "ballerinax"
name = "azure_eventhub"
version = "0.1.3"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Azure","Eventhub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.eventhub"
