name: CI_pull_request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args:
            pack ./eventhub
        env: 
          SAS_KEY_NAME: ${{ secrets.SAS_KEY_NAME }}
          SAS_KEY: ${{ secrets.SAS_KEY }}
          RESOURCE_URI: ${{ secrets.RESOURCE_URI }}
      - name: Ballerina Tests
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args:
            test ./eventhub
        env: 
          SAS_KEY_NAME: ${{ secrets.SAS_KEY_NAME }}
          SAS_KEY: ${{ secrets.SAS_KEY }}
          RESOURCE_URI: ${{ secrets.RESOURCE_URI }}
